FROM golang:1.7
RUN mkdir -p $GOPATH/src/github.com/pullrequestrfb/ && \
    curl https://glide.sh/get | sh
COPY . $GOPATH/src/github.com/pullrequestrfb/omalley/
WORKDIR $GOPATH/src/github.com/pullrequestrfb/omalley
RUN glide install
ENTRYPOINT ["go"]
